# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true

    python:
        code_rating: true
        duplicate_code: true

    ruby:
        code_rating: true
        duplicate_code: true

tools:
    external_code_coverage: false
    php_code_coverage: true

build:
    tests:
        override:
            -
                command: phpunit --coverage-clover clover
