language: php

php:
    - 5.6
    - 7.0
    - nightly

sudo: true

script:
    - phpunit --coverage-php /tmp/coverage.php
 #   - wget https://scrutinizer-ci.com/ocular.phar
 #   - php ocular.phar code-coverage:upload --format=php /tmp/coverage.php

notifications:
  email: false

