language: php

php:
    - 5.6
    - 7.0
    - nightly

sudo: false

script:
    - phpunit --coverage-php coverage.php
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php coverage.clover

notifications:
  email: false

