language: php
php:
  - 5.5
  - 5.4
  - hhvm
script: phpunit Test.php
# script: phpunit Test2.php
#script: phpunit --coverage-clover=coverage.clover

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

#after_script:
#    - wget https://scrutinizer-ci.com/ocular.phar
#    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

sudo: false
