language: php

php:
    - 5.6
    - 7.0
    - nightly

sudo: false

script:

    - phpunit --configuration build

notifications:
  email: false

phpunit --coverage-clover=coverage.clover
wget https://scrutinizer-ci.com/ocular.phar
php ocular.phar code-coverage:upload --format=php-clover coverage.clover
